spring:
  datasource:
    url: jdbc:h2:file:/Users/huangyijie/dev/workspace/github/largierj/db
  h2:
    console:
      enabled: true
jwt:
  base64-secret: VGhpcyUyMGlzJTIwQ2hhbnRhbCUyMExhcmdpZXIuY29t
  token-validity-in-seconds: 3600
log:
  path: ./logs
  prefix: largier-dev
upload:
  location: ./upload
logging:
  config: /Users/huangyijie/dev/workspace/github/largierj/support/logback-spring.xml
